# Font configuration
hints:
  alphabet: "dfjk"
  enabled:
    - regex: '([0-9a-f]{12,128})|([[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3})'
      action: Copy
      post_processing: false
      mouse:
        enabled: true
      binding:
        key: I
        mods: Control|Shift
    - regex: "(magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
              [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`()]+"
      command: xdg-open
      post_processing: false
      mouse:
        enabled: true
      binding:
        key: U
        mods: Control|Shift
font:
  # Normal (roman) font face
  normal:
    # Font family
    #
    # Default:
    # family: Glass TTY VT220
    # family: Fira Code
    family: Roboto Mono

    # The `style` can be specified to pick a specific face.
    #style: Regular
  # Point size
  # size: 20
  # size: 16
  size: 14
  # size: 12
colors:
  primary:
    background: '#2e3440'
    foreground: '#d8dee9'
    dim_foreground: '#a5abb6'
  cursor:
    text: '#2e3440'
    cursor: '#d8dee9'
  vi_mode_cursor:
    text: '#2e3440'
    cursor: '#ffdee9'
  selection:
    # text: CellForeground
    background: '#a3be8c'
  search:
    matches:
      # foreground: CellBackground
      background: '#88c0d0'
    bar:
      background: '#434c5e'
      foreground: '#d8dee9'
  normal:
    black: '#3b4252'
    red: '#bf616a'
    green: '#a3be8c'
    yellow: '#ebcb8b'
    blue: '#81a1c1'
    magenta: '#b48ead'
    cyan: '#88c0d0'
    white: '#e5e9f0'
  bright:
    black: '#4c566a'
    red: '#bf616a'
    green: '#a3be8c'
    yellow: '#ebcb8b'
    blue: '#81a1c1'
    magenta: '#b48ead'
    cyan: '#8fbcbb'
    white: '#eceff4'
  dim:
    black: '#373e4d'
    red: '#94545d'
    green: '#809575'
    yellow: '#b29e75'
    blue: '#68809a'
    magenta: '#8c738c'
    cyan: '#6d96a5'
    white: '#aeb3bb'
