[hints]
alphabet="dfjk"
[[hints.enabled]]
regex="([0-9a-f]{12,128})|([[:digit:]]{1,3}\\.[[:digit:]]{1,3}\\.[[:digit:]]{1,3}\\.[[:digit:]]{1,3})"
action="Copy"
binding={key="i",mods="Control|Shift"}

[[hints.enabled]]
regex = "(magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`()]+"
command = "xdg-open"
post_processing = false
persist = false
mouse = { enabled = true }
binding = { key = "f", mods = "Control | Shift" }

[font]
normal = { family= "Roboto Mono", style="Regular"}
size = 11.0

#
    #    # Default:
    #        # family: Glass TTY VT220
    #            # family: Fira Code
    #                family: Roboto Mono
    #                    family: CMU Typewriter Text
    #
    #                        # The `style` can be specified to pick a specific face.
    #                            #style: Regular
    #                              # Point size
    #                                # size: 20
    #                                  # size: 16
    #                                    size: 14
    #                                      # size: 12

[colors.primary]
background = "#2e3440"
foreground = "#d8dee9"

[colors.cursor]
text= "#2e3440"
cursor= "#d8dee9"
[colors.normal]
black= '#3b4252'
red= '#bf616a'
green= '#a3be8c'
yellow= '#ebcb8b'
blue= '#81a1c1'
magenta= '#b48ead'
cyan= '#88c0d0'
white= '#e5e9f0'

[colors.hints.start]
foreground= "#d8dee9"
background= "#bf616a"
[colors.hints.end]
foreground= "#d8dee9"
background= "#bf616a"

[scrolling]
history = 100000
