#!/bin/bash


batLevel=$(upower -i $(upower -e | grep '/battery') | grep --color=never -E "percentage"| awk '{print $2}'| sed -e 's/%//g')
state=$(upower -i $(upower -e | grep '/battery') | grep --color=never -E "state"| awk '{print $2}'| sed -e 's/%//g')






case $state in
    "discharging")
	stateSymbol=
	timeTo=$(upower -i $(upower -e | grep '/battery')|grep 'time to empty'|awk '{print $4 " "  $5}');;
    "charging")
	stateSymbol=
	timeTo=$(upower -i $(upower -e | grep '/battery')|grep 'time to full'|awk '{print $4 " "  $5}');;
esac

if [ "$batLevel" -eq "100" ];
then
    symbol=
    echo $stateSymbol $symbol $batLevel% $timeTo
    echo ""
    echo "#aaFF22"
elif [ "$batLevel" -ge 75 ];
then
    symbol=
    echo $stateSymbol $symbol $batLevel% $timeTo
    echo ""
    echo "#00aa00"
    
elif [ "$batLevel" -ge 50 ];
then
    symbol=
    echo $stateSymbol $symbol $batLevel% $timeTo
    echo ""
    echo "#ffff00"
elif [ "$batLevel" -ge 20 ];
then
    symbol=
    echo $stateSymbol $symbol $batLevel% $timeTo
    echo ""
    echo "#ffa500"
elif [ "$batLevel" -lt 20 ]
then
    symbol=
    echo $stateSymbol $symbol $batLevel% $timeTo
    echo ""
    echo "#ff0000"
else
    symbol=?
fi




