#!/bin/bash

status=$(echo $(mpc --host='/home/accacio/.config/mpd/socket' status|sed -n 2p|cut -d " " -f 1))

titleName=$(ncmpcpp -q --current-song='%t')
titleName=${titleName}
artistName=$(ncmpcpp -q --current-song='%a')
# artistName=${artistName::10}

path=$(ncmpcpp -q --current-song='%D')
albumName=$(ncmpcpp -q --current-song='%b')

albumNameNoDots=$(echo $albumName|sed "s/[\,\.]/ /g")

case $path in
    *"podcast"*)
	first=$titleName
	second=$albumName
	;;
    *)
	first=$titleName
	second=$artistName
	;;
esac

#full text
case $status  in
    "[playing]"| "[paused]")
	echo  $first - $second
	;;
    *)
	echo ⏹
	;;
esac

echo ""

case $status  in
    "[playing]")
	echo "#aaFF22"
	;;
    "[paused]")
	echo "#999999"
	;;
esac

case $BLOCK_BUTTON in
    1) i3-msg exec "i3-sensible-terminal -e ncmpcpp";;
    2) i3-msg exec "i3-sensible-terminal -e ncmpcpp -s outputs";;
esac
