#!/bin/bash

status=$(echo $(mpc status|sed -n 2p|cut -d " " -f 1))

#full text
case $status  in
    "[playing]"| "[paused]")
	echo  $(ncmpcpp -q --current-song="$1%t - %a$9")
	;;
    *)
	echo 
	;;
esac

echo ""

case $status  in
    "[playing]")
	echo "#aaFF22"
	;;
    "[paused]")
	echo "#999999"
	;;
esac

case $BLOCK_BUTTON in
    1) i3-sensible-terminal -e ncmpcpp;;
esac
