#!/bin/sh
cd "$HOME"/.calcurse/

# Do not do anything when synchronizing with a CalDAV server.
[ -f caldav/lock ] && exit

# Run the CalDAV synchronization script in the background.
if [ -d caldav -a -x "$(which calcurse-caldav)" ]; then
    (
        date="$(date +'%b %d %H:%M:%S')"
        echo "$date Running calcurse-caldav from the pre-load hook..."
        calcurse-caldav
        echo
    ) >>caldav/log 2>&1 &
fi

syncOrgCalcurse -c
