#!/bin/bash
case $BLOCK_BUTTON in
    1) ;;
    3) ;;
esac

batLevel=$(upower -i $(upower -e | grep '/battery') | grep --color=never -E "percentage"| awk '{print $2}'| sed -e 's/%//g')
state=$(upower -i $(upower -e | grep '/battery') | grep --color=never -E "state"| awk '{print $2}'| sed -e 's/%//g')

case $state in
    "discharging") stateSymbol=;;
    "charging") stateSymbol=
esac

if [ "$batLevel" -eq "100" ];
then
    symbol=
    echo $stateSymbol $symbol $batLevel %
    echo ""
    echo "#aaFF22"
elif [ "$batLevel" -ge 75 ];
then
    symbol=
    echo $stateSymbol $symbol $batLevel %
    echo ""
    echo "#00aa00"
    
elif [ "$batLevel" -ge 50 ];
then
    symbol=
    echo $stateSymbol $symbol $batLevel %
    echo ""
    echo "#ffff00"
elif [ "$batLevel" -ge 20 ];
then
    symbol=
    echo $stateSymbol $symbol $batLevel %
    echo ""
    echo "#ffa500"
elif [ "$batLevel" -lt 20 ]
then
    symbol=
    echo $stateSymbol $symbol $batLevel %
    echo ""
    echo "#ff0000"
else
    symbol=?
fi




