#!/bin/bash

$(xrandr| awk '/ connected|+/ {printf "%s ",$1}'|awk '{
internName=$1
internResol=$2
internX=$2
internY=$2
sub(/x.*/,"",internX)
sub(/.*x/,"",internY)
externName=$3
externResol=$4
externX=$4
externY=$4
sub(/x.*/,"",externX)
sub(/.*x/,"",externY)
print "xrandr --output " externName " --mode " externResol " --pos " internX "x0 --output " internName " --primary --mode " internResol " --pos 0x0"}')

WS1=$(head ~/dots/workspaceNames -n 1 | tail -n 1)
WS2=$(head ~/dots/workspaceNames -n 2 | tail -n 1)
WS3=$(head ~/dots/workspaceNames -n 3 | tail -n 1)
WS4=$(head ~/dots/workspaceNames -n 4 | tail -n 1)
WS5=$(head ~/dots/workspaceNames -n 5 | tail -n 1)
WS6=$(head ~/dots/workspaceNames -n 6 | tail -n 1)
WS7=$(head ~/dots/workspaceNames -n 7 | tail -n 1)
WS8=$(head ~/dots/workspaceNames -n 8 | tail -n 1)
WS9=$(head ~/dots/workspaceNames -n 9 | tail -n 1)
WS10=$(head ~/dots/workspaceNames -n 10 | tail -n 1)

extern=$(xrandr|grep connected|awk '{print $1}'|head -n 2|tail -n 1)
i3-msg "workspace "$WS10", move workspace to output $extern"
i3-msg "workspace "$WS9", move workspace to output $extern"
i3-msg "workspace "$WS8", move workspace to output $extern"
i3-msg "workspace "$WS7", move workspace to output $extern"
i3-msg "workspace "$WS6", move workspace to output $extern"


intern=$(xrandr|grep connected|awk '{print $1}'|head -n 1|tail -n 1)
i3-msg "workspace "$WS5", move workspace to output $intern"
i3-msg "workspace "$WS4", move workspace to output $intern"
i3-msg "workspace "$WS3", move workspace to output $intern"
i3-msg "workspace "$WS2", move workspace to output $intern"
i3-msg "workspace "$WS1", move workspace to output $intern"


