#!/bin/bash

$(xrandr| awk '/ connected|+/ {printf "%s ",$1}'|awk '{
internName=$1
internResol=$2
internX=$2
internY=$2
sub(/x.*/,"",internX)
sub(/.*x/,"",internY)
externName=$3
externResol=$4
externX=$4
externY=$4
sub(/x.*/,"",externX)
sub(/.*x/,"",externY)
print "xrandr --output " internName " --mode " internResol " --output " externName " --off"}')

