#!/bin/bash
case $BLOCK_BUTTON in
    1) ~/dots/scripts/changeSoundOutput >/dev/null;;
    3) pavucontrol;;
esac


output=$(pactl list short sink-inputs|head -n 1|cut -f2)

echo Vol $(pactl list sinks | grep "Sink #$output" -A 9|tail -n 1|awk '{print $5}') Out: $output
echo ""
status=$(pactl list sinks | grep "Sink #$output" -A 8|tail -n 1|awk '{print $2}')
case $status  in
    "yes")
	echo "#999999"
	;;
    "no")
	echo "#aaFF22"
	;;
esac




